services:
  - type: web
    name: youtube-audio-downloader
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FFMPEG_PATH
        value: /opt/render/project/src/bin/ffmpeg
